// Package session issues and verifies the session tokens of the play API
// (docs/UNITY-INTEGRATION.md section 2) and defines the device verifier the
// replicated log stores in place of a device secret.
//
// A token is "v1.<key id>.<payload>.<mac>". The payload is the base64url
// encoding, without padding, of the JSON object
// {"pid":...,"did":...,"iat":...,"exp":...} with its fields in that order
// and no whitespace; the mac is the base64url encoding, without padding, of
// HMAC-SHA256 under the named key over everything before the last dot. A
// Keyring's first key signs and every key verifies, which lets keys rotate
// without ending sessions. No key is compiled in: arena reads the keyring
// from the ARENA_SESSION_KEYS environment variable or from the file named
// by its -session-keys-file flag, and never logs it.
//
// The package reads no clock and starts no goroutines; callers pass the
// time.
package session

import (
	"errors"
	"time"
)

// Token format and limits.
const (
	// Version is the first dot-separated part of every token.
	Version = "v1"
	// DefaultTTL is a token's lifetime when arena's -session-ttl is unset.
	DefaultTTL = time.Hour
	// MaxTTL bounds a token's lifetime; a token whose expiry is further
	// than MaxTTL after its issue time does not verify.
	MaxTTL = 24 * time.Hour
	// Leeway is the clock difference between replicas that verification
	// tolerates on the issue time and on the expiry.
	Leeway = 30 * time.Second
	// MinKeyBytes is the shortest key a Keyring accepts.
	MinKeyBytes = 32
	// MaxKeyIDLen bounds a key id: 1 to 16 characters from a-z, 0-9 and
	// '-'.
	MaxKeyIDLen = 16
	// EnvKeys names the environment variable holding a keyring as
	// "id=hex,id=hex", the signing key first.
	EnvKeys = "ARENA_SESSION_KEYS"
)

// Device credentials, generated by the client at first launch.
const (
	// DeviceIDLen is the length of a device id: lower-case hex of 16 random
	// bytes.
	DeviceIDLen = 32
	// DeviceSecretLen is the length of a device secret: lower-case hex of 32
	// random bytes.
	DeviceSecretLen = 64
	// VerifierDomain prefixes, with a zero byte, the SHA-256 input of a
	// device verifier; the 32 bytes the device secret encodes follow.
	VerifierDomain = "paxos-arena/device/v1"
)

// KeyID names a key inside a token.
type KeyID string

// Key is one HMAC-SHA256 key.
type Key struct {
	// ID is written into every token the key signs.
	ID KeyID
	// Secret holds at least MinKeyBytes bytes.
	Secret []byte
}

// Keyring holds the keys a replica signs and verifies with. Keys[0] signs
// new tokens; a token naming any key of the ring verifies. A key is added to
// every replica's ring before any replica signs with it, and removed only
// after the tokens it signed have expired.
type Keyring struct {
	// Keys lists the keys, the signing key first.
	Keys []Key
}

// Claims are the contents of a token.
type Claims struct {
	// Player is the player the token authenticates.
	Player string `json:"pid"`
	// Device is the device the player is bound to.
	Device string `json:"did"`
	// IssuedAtMs is the issue time in Unix milliseconds, as stamped by the
	// leader that applied the session command.
	IssuedAtMs int64 `json:"iat"`
	// ExpiresAtMs is the expiry in Unix milliseconds.
	ExpiresAtMs int64 `json:"exp"`
}

// Verifier is SHA-256 over VerifierDomain, a zero byte and the 32 bytes of a
// device secret. The log stores it; the secret never leaves the request
// that carried it.
type Verifier [32]byte

// Reasons a token does not verify. The play API answers ErrExpired with 401
// session_expired and every other one with 401 session_invalid.
var (
	// ErrMalformed is a token that is not four dot-separated parts of the
	// right shape, or whose payload is not the claims object.
	ErrMalformed = errors.New("session: the token is malformed")
	// ErrUnknownKey is a token naming a key this replica does not hold.
	ErrUnknownKey = errors.New("session: the token names a key this replica does not hold")
	// ErrBadMAC is a token whose mac does not match its contents.
	ErrBadMAC = errors.New("session: the token's mac does not verify")
	// ErrExpired is a token whose expiry, plus Leeway, has passed.
	ErrExpired = errors.New("session: the token has expired")
	// ErrNotYetValid is a token issued more than Leeway in the future.
	ErrNotYetValid = errors.New("session: the token was issued in the future")
	// ErrLifetime is a token whose lifetime exceeds MaxTTL.
	ErrLifetime = errors.New("session: the token's lifetime exceeds the maximum")
)

// Reasons a keyring is refused when arena starts.
var (
	// ErrNoKeys is an empty keyring.
	ErrNoKeys = errors.New("session: the keyring has no key")
	// ErrWeakKey is a key shorter than MinKeyBytes.
	ErrWeakKey = errors.New("session: a key is shorter than 32 bytes")
	// ErrBadKeyID is a key id that is not 1 to 16 characters from a-z, 0-9
	// and '-'.
	ErrBadKeyID = errors.New("session: a key id is not 1 to 16 characters from a-z, 0-9 and '-'")
	// ErrDuplicateKeyID is a keyring in which two keys share an id.
	ErrDuplicateKeyID = errors.New("session: two keys share an id")
)
